// Centralized enums so model files, validators, and controllers
// never hand-type role/status strings in more than one place.

export const ROLES = Object.freeze({
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  CASHIER: 'CASHIER',
  TECHNICIAN: 'TECHNICIAN',
  CUSTOMER: 'CUSTOMER',
});
export const ROLE_VALUES = Object.values(ROLES);

// Roles that belong to a store's staff (vs. an end customer)
export const STAFF_ROLES = [ROLES.OWNER, ROLES.MANAGER, ROLES.CASHIER, ROLES.TECHNICIAN];

export const WARRANTY_START_TYPES = Object.freeze({
  PURCHASE_DATE: 'PURCHASE_DATE',
  DELIVERY_DATE: 'DELIVERY_DATE',
  INSTALLATION_DATE: 'INSTALLATION_DATE',
  ACTIVATION_DATE: 'ACTIVATION_DATE',
});
export const WARRANTY_START_TYPE_VALUES = Object.values(WARRANTY_START_TYPES);

export const DURATION_UNITS = Object.freeze({
  DAYS: 'DAYS',
  MONTHS: 'MONTHS',
  YEARS: 'YEARS',
});
export const DURATION_UNIT_VALUES = Object.values(DURATION_UNITS);

export const WARRANTY_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  CLAIMED: 'CLAIMED',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED',
});
export const WARRANTY_STATUS_VALUES = Object.values(WARRANTY_STATUSES);

export const CLAIM_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_REPAIR: 'IN_REPAIR',
  RESOLVED: 'RESOLVED',
});
export const CLAIM_STATUS_VALUES = Object.values(CLAIM_STATUSES);

export const SERVICE_STATUSES = Object.freeze({
  CREATED: 'CREATED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFIED: 'VERIFIED',
  ASSIGNED: 'ASSIGNED',
  TECHNICIAN_VISIT: 'TECHNICIAN_VISIT',
  DIAGNOSIS: 'DIAGNOSIS',
  REPAIR_IN_PROGRESS: 'REPAIR_IN_PROGRESS',
  WAITING_FOR_PART: 'WAITING_FOR_PART',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});
export const SERVICE_STATUS_VALUES = Object.values(SERVICE_STATUSES);

export const OTP_PURPOSES = Object.freeze({
  LOGIN: 'LOGIN',
  WARRANTY_VERIFICATION: 'WARRANTY_VERIFICATION',
  SERVICE_REQUEST: 'SERVICE_REQUEST',
  OWNERSHIP_TRANSFER: 'OWNERSHIP_TRANSFER',
});
export const OTP_PURPOSE_VALUES = Object.values(OTP_PURPOSES);

export const NOTIFICATION_CHANNELS = Object.freeze({
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  IN_APP: 'IN_APP',
});
export const NOTIFICATION_CHANNEL_VALUES = Object.values(NOTIFICATION_CHANNELS);

export const PAYMENT_METHODS = Object.freeze({
  CASH: 'CASH',
  CARD: 'CARD',
  UPI: 'UPI',
  NET_BANKING: 'NET_BANKING',
  WALLET: 'WALLET',
  OTHER: 'OTHER',
});
export const PAYMENT_METHOD_VALUES = Object.values(PAYMENT_METHODS);

export const AUDIT_ACTIONS = Object.freeze({
  INVOICE_CREATED: 'INVOICE_CREATED',
  WARRANTY_REGISTERED: 'WARRANTY_REGISTERED',
  WARRANTY_MODIFIED: 'WARRANTY_MODIFIED',
  WARRANTY_CLAIM_CREATED: 'WARRANTY_CLAIM_CREATED',
  WARRANTY_CLAIM_UPDATED: 'WARRANTY_CLAIM_UPDATED',
  SERVICE_STATUS_CHANGED: 'SERVICE_STATUS_CHANGED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  STORE_UPDATED: 'STORE_UPDATED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
});
export const AUDIT_ACTION_VALUES = Object.values(AUDIT_ACTIONS);

export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE: 'DUPLICATE',
  RATE_LIMITED: 'RATE_LIMITED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  WARRANTY_NOT_FOUND: 'WARRANTY_NOT_FOUND',
  WARRANTY_EXPIRED: 'WARRANTY_EXPIRED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
});
